# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    # Use Python 3.11 with pip — no conda needed.
    # docs/conf.py mocks all heavy imports (PySide6, pyqtgraph, neo, etc.)
    # so the docs build never needs the full runtime environment.
    python: "3.11"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

python:
  install:
    # Install the package + all Sphinx/extension deps declared in [docs] extras.
    - method: pip
      path: .
      extra_requirements:
        - docs
