# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    # Use mambaforge so that the conda environment.yml (name: synaptipy) is
    # recreated on ReadTheDocs with all runtime + docs dependencies.
    python: "mambaforge-23.1"
  # System packages required even in a headless doc build
  apt_packages:
    - libgl1
    - libglib2.0-0

# Recreate the synaptipy conda environment from environment.yml.
# All Sphinx / MyST / RTD-theme deps are listed there under pip:.
conda:
  environment: environment.yml

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

python:
  install:
    # Install the package itself (editable) so autodoc can import it.
    - method: pip
      path: .
      extra_requirements:
        - docs
